spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdbbatch
    username: postgres
    password: postgres

  batch:
    jdbc:
      initialize-schema: never

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.zipsoon.zipsoonbatch.config.typehandler

logging:
  level:
    org.springframework.batch: DEBUG
    com.zipsoon.zipsoonbatch: DEBUG

naver:
  land:
    base-url: https://new.land.naver.com/api
    auth-token: ${NAVER_AUTH_TOKEN}