spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

jwt:
  secret-key: ${PROD_JWT_SECRET}

logging:
  file:
    name: /var/log/zipsoon/zipsoon-api.log
  level:
    root: INFO
    com.zipsoon.api: INFO

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false