spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

logging:
  file:
    name: ./logs/zipsoon-api.log
  level:
    root: INFO
    com.zipsoon.api: INFO