spring:
  datasource:
    url: ${DEV_DB_JDBC_URI}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

jwt:
  secret-key: ${DEV_JWT_SECRET}

logging:
  file:
    name: /var/log/zipsoon/zipsoon-api.log
  level:
    root: INFO
    com.zipsoon.api: DEBUG