spring:
  datasource:
    url: ${DEV_DB_JDBC_URI}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

logging:
  file:
    name: ./logs/zipsoon-api.log
  level:
    root: INFO
    com.zipsoon.api: DEBUG