spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

logging:
  file:
    name: /var/log/zipsoon/batch.log
  level:
    root: INFO
    org.springframework.batch: INFO
    com.zipsoon.batch: INFO