spring:
  datasource:
    url: ${DEV_DB_JDBC_URI}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

logging:
  file:
    name: ./logs/zipsoon-batch.log
  level:
    root: DEBUG
    org.springframework.batch: DEBUG
    com.zipsoon.batch: DEBUG