spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zipsoon_batch_dev
    username: postgres
    password: postgres

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: never

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.zipsoon.common.domain

logging:
  level:
    org.springframework.batch: DEBUG
    com.zipsoon.batch: DEBUG

naver:
  land:
    base-url: https://new.land.naver.com/api
    auth-token: ${NAVER_AUTH_TOKEN}
