spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdbbatch
    username: postgres
    password: postgres

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.zipsoon.zipsoonapp.config.typehandler
#  type-aliases-package: com.zipsoon.zipsoonapp.domain
